build:
	docker build -t index.alauda.cn/fanlin/browser-%BROWSER%-%VERSION% .
run:
	docker run -P --rm index.alauda.cn/fanlin/browser-%BROWSER%-%VERSION%
push:
	docker push index.alauda.cn/fanlin/browser-%BROWSER%-%VERSION%
clean:
	for i in $$(docker images | grep "<none>" | awk "{print \$$3}"); do docker rmi -f $$i; done
